//This is esewa API integration point
//PAN=9028798347637436
// import React, { useState } from 'react';

// const PaymentButton = () => {
//   const [paymentStatus, setPaymentStatus] = useState(null);

//   const handlePayment = () => {
//     // Make an API call to your server to generate a unique token for the transaction
//     // Use the token to make an inquiry request to eSewa and get the payment parameters
//     // Redirect to the eSewa payment page with the payment parameters and the token

//     const token = '123456789'; // Replace with your actual token generated by your server
//     const amount = 1000; // Replace with the actual payment amount
//     const successUrl = 'https://yourapp.com/success'; // Replace with your actual success URL
//     const failureUrl = 'https://yourapp.com/failure'; // Replace with your actual failure URL

//     const paymentUrl = `https://uat.esewa.com.np/epay/main?amt=${amount}&pid=${token}&scd=EPAYTEST&su=${successUrl}&fu=${failureUrl}`;

//     window.location.href = paymentUrl;
//   };

//   return (
//     <div>
//       {paymentStatus === 'success' && <p>Payment successful!</p>}
//       {paymentStatus === 'failure'' && <p>Payment failed. Please try again.</p>}
//       <button onClick={handlePayment}>Pay Now</button>
//     </div>
//   );
// };

// export default PaymentButton;

{
    /* scd parameter is used to pass the merchant ID. In the example code, the merchant ID is set to EPAYTEST, which is a test merchant ID provided by eSewa for testing purposes. You should replace this with your actual merchant ID provided by eSewa for your production environment.
const paymentUrl = `https://uat.esewa.com.np/epay/main?amt=${amount}&pid=${token}&scd=EPAYTEST&su=${successUrl}&fu=${failureUrl}`; */
}
